name: Deploy Backend to Somee
on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'

jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          # Đã điền thông tin của bạn
          server: dss.somee.com
          username: nhatnguyen123
          
          # Dùng chung mật khẩu với Frontend
          password: ${{ secrets.FTP_PASSWORD }}
          
          local-dir: ./backend/
          
          # QUAN TRỌNG: Đưa Backend vào thư mục "api"
          server-dir: /www.DSS.somee.com/api/
